name: Publish Libs

on:
  push:
    branches: [prod]
  pull_request:
    branches: [prod]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@shyland-dev'

      - name: Instalar dependências
        run: npm ci

      - name: Build das libs
        run: npm run build

      - name: Permitir execução do script
        run: chmod +x .github/scripts/publish-pkg.sh

      - name: Publicar @shyland-dev/ui
        if: github.event_name == 'push'
        run: .github/scripts/publish-pkg.sh src/ui/dist/ui
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publicar @shyland-dev/utils
        if: github.event_name == 'push'
        run: .github/scripts/publish-pkg.sh src/utils/dist/utils
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
